{{- if .Values.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "bots.fullname" . }}
spec:
  selector:
    matchLabels:
      app: {{ include "bots.fullname" . }}
  endpoints:
  - port: http
{{- end }}
